version: '3.4'
services:
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - skiq-data:/sidekiq
    networks:
      - docker_elk

  postgres:
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    extends:
      file: docker/pg_compose.yml
      service: postgres

  elasticsearch:
    volumes:
      - es-data:/usr/share/elasticsearch/data
    extends:
      file: docker/elastic_compose.yml
      service: elasticsearch

  redis:
    extends:
      file: docker/redis_compose.yml
      service: redis

volumes:
  db-data:
  es-data:
  skiq-data:


networks:
  docker_elk:
    driver: bridge
