version: "3.4"
services:
  elasticsearch:    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1    
    environment:
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - discovery.type=single-node
      - bootstrap.memory_lock=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk        
