version: "2.0"
services:
  elasticsearch:
    platform: linux/x86_64
    image: elasticsearch:7.6.2
    environment:
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - discovery.type=single-node
      - bootstrap.memory_lock=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
  kibana:
    platform: linux/x86_64
    image: kibana:7.6.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - docker_elk
      
networks:
  docker_elk:
    driver: bridge