version: "3.0"
services:
  kibana:
      platform: linux/x86_64
      image: kibana:7.6.2
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - docker_elk