default: &default
  host: <%= ENV['ECOM_DATABASE_HOST'] %>
  port: <%= ENV['ECOM_DATABASE_PORT'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['ECOM_DATABASE_USERNAME'] %>
  password: <%= ENV['ECOM_DATABASE_PASSWORD'] %>
  
development:
  <<: *default
  username: ecomadmin
  database: ecom_development
  password: ecomdev@123

test:
  <<: *default
  username: ecomtestadmin
  database: ecom_test
  password: ecomtest@123